=== hoangthelam/XML/src/xml/bangghidiem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bangghidiem (hovaten, ngaysinh, lop, quequan, chuyennganh, khoa, hedaotao, khoahoc, ketqua, diemtb)>
<!ELEMENT hovaten (#PCDATA)>
<!ELEMENT ngaysinh (#PCDATA)>
<!ELEMENT lop (#PCDATA)>
<!ELEMENT quequan (#PCDATA)>
<!ELEMENT chuyennganh (#PCDATA)>
<!ELEMENT khoa (#PCDATA)>
<!ELEMENT hedaotao (#PCDATA)>
<!ELEMENT khoahoc (#PCDATA)>
<!ELEMENT ketqua (hocphan+)>
<!ELEMENT hocphan (tenhp, sotc, diemso, diemchu)>
<!ELEMENT tenhp (#PCDATA)>
<!ELEMENT sotc (#PCDATA)>
<!ELEMENT diemso (#PCDATA)>
<!ELEMENT diemchu (#PCDATA)>
<!ELEMENT diemtb (#PCDATA)>

<!ATTLIST bangghidiem msv CDATA #REQUIRED>
<!ATTLIST bangghidiem gioitinh (Nam|Nu) #REQUIRED>
<!ATTLIST bangghidiem ngay CDATA #REQUIRED>
<!ATTLIST bangghidiem thang (1|2|3|4|5|6|7|8|9|10|11|12) #REQUIRED>
<!ATTLIST bangghidiem nam CDATA #REQUIRED>
<!ATTLIST hocphan stt CDATA #REQUIRED>

=== hoangthelam/XML/src/xml/bangghidiem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bangghidiem SYSTEM "bangghidiem.dtd">

<bangghidiem msv="19T1021198" gioitinh="Nam" ngay="10" thang="2" nam="2023">
    <hovaten>Hoang The Lam</hovaten>
    <ngaysinh>02/08/2001</ngaysinh>
    <lop>K43_D2</lop>
    <quequan>TT-Hue</quequan>
    <chuyennganh>Cong nghe phan mem</chuyennganh>
    <khoa>CNTT</khoa>
    <hedaotao>Chinh quy</hedaotao>
    <khoahoc>K43</khoahoc>
    <ketqua>
        <hocphan stt="1">
            <tenhp>XML va ung dung</tenhp>
            <sotc>3</sotc>
            <diemso>10</diemso>
            <diemchu>Muoi</diemchu>
        </hocphan>
        <hocphan stt="2">
            <tenhp>He co so du lieu phan tan</tenhp>
            <sotc>2</sotc>
            <diemso>10</diemso>
            <diemchu>Muoi</diemchu>
        </hocphan>
        <hocphan stt="3">
            <tenhp>Lap trinh Web</tenhp>
            <sotc>3</sotc>
            <diemso>10</diemso>
            <diemchu>Muoi</diemchu>
        </hocphan>
    </ketqua>
    <diemtb>2.5</diemtb>
</bangghidiem>
